///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package SpringAzureOpenAI.ChatTemplate;
//
//import SpringAzureOpenAI.Chat.App;
//import org.junit.Test;
//import static org.junit.Assert.*;
//
//public class AppTest {
//
//}
